spring:
  application:
    name: eureka-server-single

server:
  port: 20011
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false # 自我保护模式
    eviction-interval-timer-in-ms: 1000 # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）

  client:
    service-url:
      defaultZone: http://localhost:20011/eureka/
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    # 这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
    register-with-eureka: false
    # 设置是否从注册中心获取注册信息（缺省true）
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetch-registry: false

