eureka:
  client:
    service-url:
      defaultZone: http://localhost:20011/eureka
  instance:
    prefer-ip-address: false
     # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。turbine存在的问题：eureka.instance.hostname一致时只能检测到一个节点，会造成turbine数据不完整

server:
  port: 30011
spring:
  application:
    name: eureka-ribbon-client-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 14000