
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20011/eureka
  instance:
    prefer-ip-address: false
     # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。turbine存在的问题：eureka.instance.hostname一致时只能检测到一个节点，会造成turbine数据不完整

server:
  port: 30011
spring:
  application:
    name: eureka-ribbon-client-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true
#添加了 actuator 管理端口后，需要从该端口获取 hystrix.stream
management:
  port: 30211
  security:
    enabled: false
  context-path: /admin  #增加了该配置后，需要 http://localhost:31011/admin/health 这样获取信息
                        # hystrix 也需要从 http://localhost:30211/admin/hystrix.stream获取

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 14000