eureka:
  client:
    service-url:
      defaultZone: http://localhost:20011/eureka
server:
  port: 30010
spring:
  application:
    name: eureka-fegin-consumer
feign:
  hystrix:
    enabled: true  #必须加这个，feign的hystrix才能有效