// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeReq.proto

package com.weiyu.protobuf;

public final class SubscribeProto {
  private SubscribeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weiyu_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weiyu_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weiyu_SubscribeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weiyu_SubscribeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022SubscribeReq.proto\022\005weiyu\"\\\n\020Subscribe" +
      "Request\022\020\n\010subReqID\030\001 \001(\005\022\020\n\010userName\030\002 " +
      "\001(\t\022\023\n\013productName\030\003 \001(\t\022\017\n\007address\030\004 \003(" +
      "\t\"I\n\021SubscribeResponse\022\020\n\010subReqID\030\001 \001(\005" +
      "\022\024\n\014responseCode\030\002 \001(\005\022\014\n\004desc\030\003 \001(\tB.\n\022" +
      "com.weiyu.protobufB\016SubscribeProtoP\001\242\002\005N" +
      "ettyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_weiyu_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_weiyu_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weiyu_SubscribeRequest_descriptor,
        new String[] { "SubReqID", "UserName", "ProductName", "Address", });
    internal_static_weiyu_SubscribeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_weiyu_SubscribeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weiyu_SubscribeResponse_descriptor,
        new String[] { "SubReqID", "ResponseCode", "Desc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
