// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeReq.proto

package com.weiyu.protobuf;

public interface SubscribeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weiyu.SubscribeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 subReqID = 1;</code>
   */
  int getSubReqID();

  /**
   * <code>optional int32 responseCode = 2;</code>
   */
  int getResponseCode();

  /**
   * <code>optional string desc = 3;</code>
   */
  String getDesc();
  /**
   * <code>optional string desc = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
