// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeReq.proto

package com.weiyu.protobuf;

public interface SubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weiyu.SubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 subReqID = 1;</code>
   */
  int getSubReqID();

  /**
   * <code>optional string userName = 2;</code>
   */
  String getUserName();
  /**
   * <code>optional string userName = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>optional string productName = 3;</code>
   */
  String getProductName();
  /**
   * <code>optional string productName = 3;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>repeated string address = 4;</code>
   */
  java.util.List<String>
      getAddressList();
  /**
   * <code>repeated string address = 4;</code>
   */
  int getAddressCount();
  /**
   * <code>repeated string address = 4;</code>
   */
  String getAddress(int index);
  /**
   * <code>repeated string address = 4;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes(int index);
}
